### ISSUE TITLE
Gather various performance measurement routines in the same module

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/lookout-sdk-ml#6] opened 2018-11-19 19:21 UTC
We've got `profile` decorator in style-analyzer, `timeit` in EventListener, and probably other related things across the files. We should move them to a single module in SDK.

**Comment by vmarkovtsev** [comment] 2019-05-21 08:38
@zurk Can you please check if this is still relevant?

**Comment by zurk** [comment] 2019-05-21 09:25
well, yes and no. 
yes because it is still the case with two functions `timeit` and `profile` (I do not see any others btw).
But if you look closer they are different and do different things.
`timeit` is specific to `EventListener` by design and measures response time.

`profile` is general profiling decorator for any function, that is it measures not only spent time
https://github.com/src-d/lookout-sdk-ml/blob/2767f72e960dcb68f2ed35440058a88a308de923/lookout/core/event_listener.py#L134-L151

 
https://github.com/src-d/style-analyzer/blob/07f643791b159e5e415cff711c44ce341bfe51ee/lookout/style/format/benchmarks/time_profile.py#L8-L28

I think we can close it.

**Closed** 2019-05-21 11:06 UTC
